/* Shared so the accordion and the FAQPage structured data can never drift
   apart — Google is quoting the same answers the page shows. */
export type Faq = { q: string; a: string };

export const faqs: Faq[] = [
  { q: "What does an inspection include?", a: "A verified inspector walks a structured room-by-room checklist — entrance, living, kitchen, bedrooms, bathrooms, balcony, electrical and utilities — marking each item Pass, Fail or Attention, with photos or short video attached to every item." },
  { q: "How quickly do I get the report?", a: "Within an hour of the visit, guaranteed. While our app is in beta, it reaches you on WhatsApp and as a PDF." },
  { q: "How do I know I can trust the inspector?", a: "Nobody walks in off the street. Every inspector is referred or scouted, then vetted in person: Aadhaar and address proof, a police-verification certificate, two references we actually call, and a supervised trial inspection. You get their name and photo on WhatsApp before the visit; nobody goes in until you confirm; every photo carries its GPS location and time; and owners rate every visit — drop below the bar and they leave the network." },
  { q: "Can a repair happen without my approval?", a: "No. A flagged issue is a question, not a work order. You approve or decline with a reason, and only then is a verified provider assigned. Every decision is written to an audit log nobody can edit." },
  { q: "Where are my photos and videos stored?", a: "In private cloud storage, served to you on signed, expiring links. Only verified, assigned users on your property can see them." },
  { q: "What does it cost?", a: "For homes up to 2 BHK: a one-time visit is ₹1,999, Care is ₹7,999 a year (4 inspections + 2 refresh cleans of the whole home) and Care+ is ₹14,999 a year (adds 2 maintenance services with repairs covered up to ₹20,000). For 3 BHK it's ₹2,499 / ₹9,999 / ₹19,999 and for 4 BHK+ it's ₹2,999 / ₹11,999 / ₹24,999. Cleaning booked on its own is priced by size and includes the inspector: refresh clean ₹1,999 / ₹2,499 / ₹2,999 / ₹3,999 / ₹4,999 and deep clean ₹4,999 / ₹5,499 / ₹6,499 / ₹7,999 / ₹9,499 for 1 to 5 BHK. Added to an inspection you are already booking, a refresh clean is +₹999 at any size and a deep clean is +₹3,999 / ₹4,499 / ₹5,499 / ₹6,499 / ₹7,499 for 1 to 5 BHK. Car ₹700, plot visit ₹1,999." },
  { q: "What exactly does the Care+ cover include?", a: "Up to ₹20,000 of repairs a year, at most ₹10,000 per incident. We pay up to ₹7,000 of parts per incident, and the rest of the cover goes to labour and miscellaneous expenses. Anything beyond the cover is quoted and only happens after you approve it. Appliance replacement, structural/civil work, pre-existing issues and cosmetic upgrades aren't covered — we still inspect and quote them, they just sit outside the ₹20,000." },
  { q: "How do you make money on repairs?", a: "Openly. When you approve a repair, you see the verified provider's quote and a flat 10% Still Yours fee on top — for example ₹3,000 + ₹300 = ₹3,300 — and you approve that exact amount. The provider gets their quote, we keep the 10%. No brokerage, no hidden commission, no marked-up bills. Repairs inside your Care+ cover carry no fee at all." },
  { q: "What's the difference between a refresh clean and a deep clean?", a: "A place that has simply been shut for a few months needs dust removed, not grease — that is a genuinely cheaper job and we price it as one. The refresh clean (₹1,999 for a 1 BHK up to ₹4,999 for a 5 BHK, two to five hours) does cobwebs, fans, floors swept and mopped, surfaces, sills and wardrobe fronts wiped, kitchen slab and hob, bathroom surfaces and the WC, and every tap and trap run so the seals don't dry out. The deep clean (₹4,999 / ₹5,499 / ₹6,499 / ₹7,999 / ₹9,499 for 1 to 5 BHK) is a crew of two to four for four to nine hours: floors machine-scrubbed, kitchen degreased down to the burner pores, bathroom tiles and grout scrubbed and the WC and taps descaled, window glass, tracks and grills, doors, skirting, switchboards, balconies — the lot. Both prices include the verified inspector for the whole job, the 42-item inspection, before and after photographs of every room and the report. There is a line-by-line comparison on the cleaning page." },
  { q: "What costs extra on a clean, and what doesn't?", a: "Cabinet exteriors and dry vacuuming of sofas and mattresses are part of both tiers at no charge. The things every app hides behind an asterisk are itemised so you choose them before you pay: cabinet interiors with utensil arrangement ₹599, chimney ₹499, fridge ₹549, microwave ₹249; mattress shampoo ₹449 per mattress, sofa wet shampoo ₹549 for a 3–4 seater, ₹699 for a 5–6 seater and ₹899 for a 7+ seater or L-shape; an extra balcony or a store/utility room ₹449 each and an extra bathroom ₹499, over and above the bedrooms, bathrooms and balconies your size already covers. Nothing is added at the door." },
  { q: "Don't you need a bucket, a power point and someone to open the door?", a: "That is exactly the list every cleaning app hands you, and it is the reason an owner abroad can never book one. The cleaning crew we book brings its own ladder, buckets, extension lead, scrubbing machine, wet-and-dry vacuum and solutions. All we need at the property is a working water supply and one power point — your inspector checks both at the start of the visit and tells you before the crew begins; if the supply is dead we reschedule and you pay nothing. And the person at the door is the inspector, going in only after you confirm." },
  { q: "Can you get the place ready before I arrive?", a: "That's what the Coming home package is for, and it's the thing no cleaning app can do — every one of them needs somebody at home to let the crew in, which is exactly what you don't have. Book two or three days before you land. Your inspector goes in once you confirm, runs the full checklist, supervises the deep-clean crew for the entire time they're in the house, and photographs every room before and after. Anything broken is flagged with a quote, and if you approve it, it's repaired before you arrive. The deep clean price already includes the inspector and the inspection, so the whole package starts at ₹4,999 for a 1 BHK." },
  { q: "Who actually does the repairs and cleaning?", a: "Rated professionals from established home-service companies, booked and paid for by us. You never deal with them or pay them directly. The person we vet in person is your inspector — they let the crew in once you confirm, stay for the whole job and photograph the work before and after. Repairs are always the professional's quote plus a flat 10% fee, shown to you before you approve." },
  { q: "Who is there when the cleaning or repair happens?", a: "Your inspector. Cleaning crews and repair providers only work during a scheduled visit, with the verified inspector on-site the whole time — from the moment they enter to the after-photos. Nobody gets your keys alone, and nothing happens behind your back." },
  { q: "How do I know the inspector actually checked every room?", a: "When you sign up you list your rooms — bedrooms, bathrooms, kitchen, balconies, parking — and every one of them is filmed and photographed, with a final walkthrough of the whole home on video before the inspector leaves. Every photo carries its GPS location and time, so you can see where and when it was taken." },
  { q: "Can I watch the visit myself?", a: "Yes. Tick \"Call me live\" at sign-up and the inspector video-calls you at the start and the end of every visit — you, your parents or your caretaker can watch live from anywhere. Every room is on recorded video anyway, and the visit is protected up to ₹1,00,000." },
  { q: "What if something is stolen or damaged during a visit?", a: "It's built so that can't happen quietly: one verified person, in only after you confirm, every room on video, GPS and time on every photo, and an exit walkthrough before they leave. Watch the exit video in your report; if anything looks off, tell us on WhatsApp — any time until your next visit. With that evidence, the Still Yours Guarantee covers theft or damage during a visit up to ₹1,00,000 — a very, very rare case with a system this tight, but if it ever happens, we pay, not you. Keep cash, jewellery and documents locked away — inspectors never open cupboards or lockers." },
  { q: "Does the inspector leave after an hour?", a: "No. The inspector stays for the entire visit, however long it takes to cover every room and item. We pay inspectors for the extra time — you never do." },
  { q: "Why not just ask a neighbour or relative to check?", a: "For a quick glance, do — a good neighbour is worth a lot. But a favour gets you an opinion, not a checklist. Someone doing you a kindness won't open the meter box, run the geyser for ten minutes or feel under the bathroom sink, and you'd feel rude asking. They also won't give you bad news straight; an inspector is paid to write down exactly what's there and is rated by you afterwards on whether they did. The bigger difference is over time: every visit runs the same checklist in the same order, so 'damp patch 4 cm in March, 11 cm in July' becomes a fact you can act on. A one-off favour can never build that comparison. And if you want your neighbour at the door, bring them — they can let the inspector in, walk the visit and get the same report you do." },
  { q: "Is this like a local property agent?", a: "No. Local agents usually inspect only if they get to broker your tenant — they take a commission and the actual checking rarely happens. Still Yours doesn't do brokerage. On repairs we charge a flat 10% fee that you see before you approve — nothing hidden in the bill. Inspection, proof and owner-approved repairs are the whole product." },
  { q: "Do you inspect plots and land?", a: "Yes. A plot visit is ₹1,999: a full boundary walk with a GPS-tagged photo of every corner, checking for encroachment, occupation, unauthorised construction, dumping and notices — report within the hour with a photo map. Book it once, or every quarter." },
  { q: "Can you check my car too?", a: "Yes — ₹700 per car, added to any visit or plan. The inspector starts it, lets it idle, checks the battery, tyres and leaks, photographs the odometer and the cover, and it all goes into the same report." },
  { q: "Which cities are live?", a: "Bengaluru is live now — homes, plots and cars across the city. We open a new city only when we have verified inspectors and repair professionals there. Next: Pune, Hyderabad and Jaipur." },
];
